name = "thevault-api"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
migrations_dir = "migrations"

kv_namespaces = [
  { binding = "VAULT_KV", id = "6836e305861a45a78d24128a07f558e5" }
]

[[d1_databases]]
binding = "thevault-db"
database_name = "thevault-db"
database_id = "375949ce-7c7d-4822-8235-461446769258"
