import { getPrompt } from "./agent-prompts";

export type AgentDefinition = {
  projectId: string;
  name: string;
  description: string;
  mode: string;
  priority: number;
  cycleBudgetMinutes: number;
  verificationCommand: string;
  model: string;
  handsOff: string[];
  rateLimit: string;
  retryMax: number;
  dataRetentionDays: number;
  piiHandling: string;
};

export const AGENT_DEFINITIONS: AgentDefinition[] = [
  // ─── EXISTING AGENTS ───
  {
    projectId: "appraiser",
    name: "AI Appraiser",
    description: "Photo-based luxury item appraisal. Value ranges, authenticity, market analysis.",
    mode: "A",
    priority: 1,
    cycleBudgetMinutes: 5,
    verificationCommand: "Output must contain valid estimatedValue and valueRangeLow/High. Confidence must be one of high/medium/low.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "auth"],
    rateLimit: "30 requests/min",
    retryMax: 3,
    dataRetentionDays: 365,
    piiHandling: "Mask seller contact info beyond unique seller ID in logs",
  },
  {
    projectId: "outreach",
    name: "Buyer Outreach",
    description: "Professional lead generation. Finds verified buyers, collectors, dealers.",
    mode: "A",
    priority: 1,
    cycleBudgetMinutes: 10,
    verificationCommand: "Each segment must be a professional type, not a fake individual. No invented names or emails.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "stripe"],
    rateLimit: "10 requests/min",
    retryMax: 3,
    dataRetentionDays: 730,
    piiHandling: "Use hashed IDs for personalization. Do not include explicit PII in agent logs. Comply with CAN-SPAM/GDPR opt-out rules.",
  },
  {
    projectId: "proverify",
    name: "ProVerify Engine",
    description: "Multi-expert verification with consensus scoring for authenticity and value.",
    mode: "A",
    priority: 1,
    cycleBudgetMinutes: 8,
    verificationCommand: "Must have 3+ expert reviews with scores 0-100. All scores marked as simulated estimates.",
    model: "gpt-4o",
    handsOff: ["users", "payments"],
    rateLimit: "10 requests/min",
    retryMax: 2,
    dataRetentionDays: 1095,
    piiHandling: "Anonymize buyer/seller info in logs. Log only anonymized sale IDs.",
  },
  {
    projectId: "content",
    name: "Content & SEO",
    description: "Product descriptions, SEO copy, marketing content for listings.",
    mode: "B",
    priority: 2,
    cycleBudgetMinutes: 5,
    verificationCommand: "Must have exactly 3 variants with correct word counts. No fabricated provenance.",
    model: "gpt-4o-mini",
    handsOff: ["users", "payments", "auth"],
    rateLimit: "30 requests/min",
    retryMax: 3,
    dataRetentionDays: 730,
    piiHandling: "Do not display seller personal data on public listings. Use hashed IDs for personalization.",
  },
  {
    projectId: "security",
    name: "Security Auditor",
    description: "Security monitoring, vulnerability audits, penetration testing.",
    mode: "A",
    priority: 1,
    cycleBudgetMinutes: 10,
    verificationCommand: "Each finding must have severity and remediation. No invented CVEs.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "production_db"],
    rateLimit: "Event-driven",
    retryMax: 3,
    dataRetentionDays: 365,
    piiHandling: "No user PII involved. Ensure internal log storage is secure.",
  },
  {
    projectId: "pricing",
    name: "Pricing Intelligence",
    description: "Market analysis and price recommendations based on real data only.",
    mode: "B",
    priority: 2,
    cycleBudgetMinutes: 7,
    verificationCommand: "Comparables must be general market knowledge only. No specific unverified sales.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "stripe"],
    rateLimit: "10 requests/min",
    retryMax: 2,
    dataRetentionDays: 1095,
    piiHandling: "No personal client data should be logged. Store valuation results (price, date) permanently.",
  },
  {
    projectId: "support",
    name: "Support Assistant",
    description: "Customer support. Answers FAQs, routes complex issues to humans.",
    mode: "B",
    priority: 3,
    cycleBudgetMinutes: 3,
    verificationCommand: "Response must be based only on provided policies. Must not fabricate policy details.",
    model: "gpt-4o-mini",
    handsOff: ["users", "payments", "auth", "personal_data"],
    rateLimit: "Realtime chat limits",
    retryMax: 3,
    dataRetentionDays: 365,
    piiHandling: "When responding, confirm identity without logging personal details. Avoid repeating full names or payment info in chat logs.",
  },
  {
    projectId: "listing",
    name: "Listing Optimizer",
    description: "Quality checks for photos, descriptions, pricing, compliance.",
    mode: "A",
    priority: 2,
    cycleBudgetMinutes: 5,
    verificationCommand: "Compliance flags must be specific. Scores 0-100 integers. No invented violations.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "production_db"],
    rateLimit: "30 requests/min",
    retryMax: 3,
    dataRetentionDays: 365,
    piiHandling: "Do not display seller personal data on public listings.",
  },
  {
    projectId: "compliance",
    name: "Compliance Monitor",
    description: "Legal/regulatory compliance review. Terms, privacy, shipping, tax.",
    mode: "B",
    priority: 2,
    cycleBudgetMinutes: 10,
    verificationCommand: "Findings must reference general regulations only. No invented section numbers.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "legal_contracts"],
    rateLimit: "Low frequency",
    retryMax: 2,
    dataRetentionDays: 2555,
    piiHandling: "If analyzing client data, mask personal identifiers in logs. Retain only case IDs, not full identity.",
  },
  {
    projectId: "social",
    name: "Social Lead Gen",
    description: "Social media intelligence. Community identification, engagement strategy.",
    mode: "A",
    priority: 3,
    cycleBudgetMinutes: 8,
    verificationCommand: "No fabricated usernames, follower counts, or metrics. Use placeholders only.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "personal_data"],
    rateLimit: "Social API limits (e.g. 60 requests/min)",
    retryMax: 3,
    dataRetentionDays: 730,
    piiHandling: "Use hashed IDs for personalization. No explicit PII in agent logs.",
  },
  // ─── NEW AGENTS FROM RESEARCH REPORT ───
  {
    projectId: "research",
    name: "Market Research",
    description: "Web intelligence. Searches for buyer interest, social discussions, and market trends.",
    mode: "A",
    priority: 2,
    cycleBudgetMinutes: 10,
    verificationCommand: "Every finding must include source URL. No fabricated URLs or posts.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "auth", "personal_data"],
    rateLimit: "60 requests/min",
    retryMax: 3,
    dataRetentionDays: 365,
    piiHandling: "Analyze only aggregate data. Never reveal individual identities in reports.",
  },
  {
    projectId: "cataloging",
    name: "Cataloging Agent",
    description: "Intake and catalog new auction items. Generates structured catalog records from item details.",
    mode: "A",
    priority: 1,
    cycleBudgetMinutes: 5,
    verificationCommand: "Must have valid title, category, description. No fabricated provenance or maker marks.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "auth"],
    rateLimit: "30 requests/min",
    retryMax: 3,
    dataRetentionDays: 365,
    piiHandling: "Mask seller name/contact beyond unique seller ID in logs. Follow GDPR for any personal seller data.",
  },
  {
    projectId: "photography",
    name: "Photography Agent",
    description: "Process and optimize images for auction listings. Crops, color-corrects, generates thumbnails.",
    mode: "A",
    priority: 2,
    cycleBudgetMinutes: 3,
    verificationCommand: "Must not alter item appearance beyond standard optimization. Quality score 0-100 required.",
    model: "gpt-4o-mini",
    handsOff: ["users", "payments", "auth", "personal_data"],
    rateLimit: "100 transformations/hour",
    retryMax: 1,
    dataRetentionDays: 90,
    piiHandling: "Ensure no personal metadata in image EXIF data.",
  },
  {
    projectId: "logistics",
    name: "Logistics Agent",
    description: "Coordinate shipping and tracking for sold items. Generates labels and schedules pickups.",
    mode: "A",
    priority: 2,
    cycleBudgetMinutes: 5,
    verificationCommand: "Must include carrier, tracking number, and insurance for items over $5,000.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "pricing", "legal"],
    rateLimit: "50 labels/min",
    retryMax: 3,
    dataRetentionDays: 90,
    piiHandling: "Use buyer address only as needed to ship. Do not include full address in non-secure logs.",
  },
  {
    projectId: "inventory",
    name: "Inventory Agent",
    description: "Track items in storage. Updates stock counts, location assignments, status transitions.",
    mode: "B",
    priority: 3,
    cycleBudgetMinutes: 3,
    verificationCommand: "Status transitions must be valid. Flag discrepancies for human review.",
    model: "gpt-4o-mini",
    handsOff: ["users", "payments", "auth", "personal_data"],
    rateLimit: "Batch (daily)",
    retryMax: 3,
    dataRetentionDays: 730,
    piiHandling: "Not applicable — manages items, not people.",
  },
  {
    projectId: "analytics",
    name: "Analytics Agent",
    description: "Data analysis and reporting. Revenue trends, forecasts, customer segment insights.",
    mode: "B",
    priority: 3,
    cycleBudgetMinutes: 8,
    verificationCommand: "All predictions must include confidence levels and ranges. No guaranteed future values.",
    model: "gpt-4o",
    handsOff: ["users", "payments", "auth", "personal_data"],
    rateLimit: "Varies with query complexity",
    retryMax: 2,
    dataRetentionDays: 365,
    piiHandling: "Analyze only aggregate data. Never reveal individual bidder identities in reports.",
  },
];

export const REQUIRED_AGENT_IDS = AGENT_DEFINITIONS.map((agent) => agent.projectId);

export function toAgentProject(def: AgentDefinition) {
  return {
    projectId: def.projectId,
    name: def.name,
    description: def.description,
    mode: def.mode,
    priority: def.priority,
    engineerCommand: getPrompt(def.projectId),
    verificationCommand: def.verificationCommand,
    cycleBudgetMinutes: def.cycleBudgetMinutes,
    handsOff: JSON.stringify(def.handsOff),
    providerId: "openai",
    model: def.model,
    active: true,
  };
}

/**
 * Returns the agent definition metadata for a given project ID.
 * Includes rate limits, retry config, data retention, and PII handling.
 */
export function getAgentMetadata(projectId: string): AgentDefinition | undefined {
  return AGENT_DEFINITIONS.find((a) => a.projectId === projectId);
}
